# 2019년 12월 6일 

!pip install watermark

%load_ext
%reload_ext
%unload_ext

In [102]:
%load_ext watermark

In [ ]:
# %reload_ext # 충돌이 일어나면 reload_Ext 써서 다시 한다. 

In [ ]:
!pip uninstall tensorboard

In [ ]:
!pip install tensorboard==2.0.0

In [103]:
%watermark -acho -d -ptensorflow,tensorboard
# 나중에 버전 확인 용도 

cho 2019-12-09 

tensorflow 2.0.0
tensorboard 2.0.0


In [14]:
# watermark보다 이쁜애
# 쓰는 패키지 보여주는 것 
!pip install version-information

In [5]:
%load_ext version_information

In [7]:
%version_information numpy, scipy, pandas, tensorflow, keras, tensorboard

Software versions
Python 3.7.3 64bit [MSC v.1915 64 bit (AMD64)]
IPython 7.4.0
OS Windows 10 10.0.17134 SP0
numpy 1.17.4
scipy 1.3.3
pandas 0.24.2
tensorflow 2.0.0
keras 2.3.0
tensorboard 2.0.0
Fri Dec 06 14:28:17 2019 ¢¥eCN©öI¡¾©ö C¡ÍA¨ª¨öA

In [24]:
# Clear any logs from previous runs
# 누적이 되므로 지워준다. 
!rm -rf ./logs/ 

In [23]:
# tensorboard --logdir mylogdir

In [1]:
import tensorflow as tf 
import datetime 
# time: 절대적 시각
# caldendar: 달 
# datetime: 시간 날짜 

In [2]:
tf.__version__
# 2.0 부터 tensorboard 쓸 수 있다. 

'2.0.0'

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

def create_model():
  return tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
  ])

In [4]:
model = create_model()
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 512)               401920    
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [6]:
# 저장될 경로
# cho="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
# 인스턴스
# 저장경로 설정 안해놓으면 현재 작업하는 경로에 저장 
# binary file -> tensorboard가 웹서브에 띄워준다. 
tensorboard_callback = tf.keras.callbacks.TensorBoard('remove')

In [7]:
model.fit(x=x_train, 
          y=y_train, 
          epochs=3, 
          validation_data=(x_test, y_test), 
          callbacks=[tensorboard_callback])

Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 21s 350us/sample - loss: 0.2209 - accuracy: 0.9350 - val_loss: 0.1008 - val_accuracy: 0.9694
Epoch 2/3
60000/60000 [==============================] - 21s 347us/sample - loss: 0.0969 - accuracy: 0.9707 - val_loss: 0.0801 - val_accuracy: 0.9762
Epoch 3/3
60000/60000 [==============================] - 20s 329us/sample - loss: 0.0698 - accuracy: 0.9779 - val_loss: 0.0693 - val_accuracy: 0.9778


In [13]:
# 현재 작업 폴더 
!pwd

/c/Users/Cho Gyung Ah/Documents/Github/image


In [ ]:
!dir

In [8]:
%load_ext tensorboard

In [11]:
# 보안이슈때문에 안나오는 경우가 있다. 
%tensorboard --logdir remove

Reusing TensorBoard on port 6006 (pid 12424), started 0:01:27 ago. (Use '!kill 12424' to kill it.)

## tensorboard_image보기

In [1]:
%load_ext tensorboard

In [2]:
%unload_ext tensorboard

The tensorboard extension doesn't define how to unload it.


In [2]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
import sklearn.metrics

In [3]:
print("TensorFlow version: ", tf.__version__)

TensorFlow version:  2.0.0


- objective 함수 

In [4]:
# Download the data. The data is already divided into train and test.
# The labels are integers representing classes.
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = \
    fashion_mnist.load_data()

# Names of the integer classes, i.e., 0 -> T-short/top, 1 -> Trouser, etc.
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 
    'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [5]:
print("Shape: ", train_images[0].shape)
print("Label: ", train_labels[0], "->", class_names[train_labels[0]])

Shape:  (28, 28)
Label:  9 -> Ankle boot


In [6]:
# Reshape the image for the Summary API.
# CNN은 3차원 
img = np.reshape(train_images[0], (-1, 28, 28, 1))

In [7]:
# Clear out any prior log data.
!rm -rf logs

# Sets up a timestamped log directory.
# logdir = "logs/train_data/" + datetime.now().strftime("%Y%m%d-%H%M%S")
# Creates a file writer for the log directory.
# create_file_write: 어디에 저장할건지 지정해준다. 
file_writer = tf.summary.create_file_writer('remove1')

# Using the file writer, log the reshaped image.
# 이건 그냥 암기해야한다. 
with file_writer.as_default():
  tf.summary.image("Training data", img, step=0)

rm: cannot remove 'logs/train': Directory not empty
rm: cannot remove 'logs/validation': Directory not empty


In [15]:
dir(tf.summary)
# SummaryWriter: summary 집어 넣는 애
# create_file_writer: djeldpekrk wjwkdgownsms rjt 

['SummaryWriter',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'audio',
 'create_file_writer',
 'create_noop_writer',
 'experimental',
 'flush',
 'histogram',
 'image',
 'record_if',
 'scalar',
 'text',
 'trace_export',
 'trace_off',
 'trace_on',
 'write']

In [24]:
# 기존에 이름이 똑같은게 있으면 에러가 난다. 
# %writefile hi

UsageError: Line magic function `%writefile` not found (But cell magic `%%writefile` exists, did you mean that instead?).


In [23]:
dir(xx.as_default())
# __exit__가 나온다. -> with 구문을 쓰라는 것 

['__abstractmethods__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_recreate_cm',
 'args',
 'func',
 'gen',
 'kwds']

In [11]:
# a.aa가 저장된다. 
with open('a.aa','w') as f:
    f.write('asdf')

In [ ]:
# 이미지 데이터가 덮어씌워진다. 
# 폴더를 만들어준다. 
xx = tf.summary.create_file_writer('hi',img)

with xx.as_default():
    # mainthred 
    tf.summary.image('adsf',img, step=0)

In [10]:
%tensorboard --logdir remove1

Reusing TensorBoard on port 6006 (pid 9072), started 0:00:55 ago. (Use '!kill 9072' to kill it.)

---

In [12]:
import datetime

In [13]:
dir(datetime)

['MAXYEAR',
 'MINYEAR',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'date',
 'datetime',
 'datetime_CAPI',
 'sys',
 'time',
 'timedelta',
 'timezone',
 'tzinfo']

In [14]:
# date 날짜를 관리해준다. 
x = datetime.date(2019,12,29)
y = datetime.date(2019,12,31)

In [15]:
z = datetime.timedelta(3)

In [16]:
x + z

datetime.date(2020, 1, 1)

In [18]:
# 사람이 읽기 쉬운 것 
datetime.datetime.now()

datetime.datetime(2019, 12, 6, 16, 9, 18, 696077)

In [19]:
import time 

In [20]:
time.time()
# 1970년부터 ms씩 증가시킨 애

1575616167.0386617

In [23]:
# strf 원하는 format으로 바꿔주는것 
datetime.datetime.strftime(x, '%d-%m-%Y')


'29-12-2019'

In [25]:
# strp 문자열로부터 형태를 객체로 만들어주는것
datetime.datetime.strptime('2019-12-13', '%Y-%m-%d')

datetime.datetime(2019, 12, 13, 0, 0)

In [ ]:
# 시간, 날짜는 python 포맷 
# dateutil은 pandas에 기본으로 깔려있다. 

---

### logdir 붙이고 다시 실행  

In [ ]:
# Clear out any prior log data.
!rm -rf logs

In [29]:
from datetime import datetime

In [32]:
# Sets up a timestamped log directory.
# 날짜시간이 너무 길어서 이름 치는게 너무 귀찮을 수 있음...
logdir = "logs/train_data/" + datetime.now().strftime("%Y%m%d-%H%M%S")
# Creates a file writer for the log directory.
# 파일이 비어있는 directory이면 에러가 나지 않는다. 
# tf.summary는 데이터 확인하는 용도로 다양한기능을 제공하고 있다.
file_writer = tf.summary.create_file_writer(logdir)

# Using the file writer, log the reshaped image.
# 최근파일에 내용이 as_default()를 이용하여 덮어진다. 
with file_writer.as_default():
  tf.summary.image("Training data", img, step=0, max_outputs=4)
# step은 이미지 부제목? 같은거 위에 뜬다. 
# step: (int64를 monotonic level 으로 바꿔준다.): 대조레벨 (흑백이라서 잘 안보임)
# max_outputs 를 4로하면 한꺼번에 사진을 4개 볼 수 있도록 도와준다. 

In [34]:
%tensorboard --logdir logs/train_data

Reusing TensorBoard on port 6006 (pid 1324), started 0:02:09 ago. (Use '!kill 1324' to kill it.)

## pytorch에도 tensorboard가 있다. 

In [ ]:
# %으로 안열고 !로 열면 load_ext 안해도 새로운 페이지에서 뜬다.
# 다만 실행시키는동안 걔속 돌아가서, 중지시켜야한다. 
!tensorboard --logdir logs/train_data

- 이미지 불러들일 때 
1. imageDataGenerator: 속도가 느려서 tensor로 불러들인다. 
image를 관리하고 싶을 때 이미지를 tensorflow는 이미지를 기본적으로 bytes형태로 쓴다. 

python은 open을 (파일 스트리밍 객체) 메모리 파일 비슷한걸 만들어써서 덮어씀. 

2. 쌩으로 tensor로 (numpy로) 불러오는 것 



bytesio, stringio같은 것들이 있다. 효과적으로 관리할 수 있음. 

GAN은 generative 모델 

matplotlib은 savefig같은게 있다. 

In [ ]:
# 학습시킬때와 학습시킬때 이미지 차원이 똑같아야한다. 

keras: callback

tensorflow: tf.summary() 데이터 확인하는 용도로 다양한기능을 제공하고 있다.

# 2019년 12월 9일

Neural Nets for Vision 


- End-To-End: 병목현상이 없어서 좋다. 

IDEA # 1
Learn features from data
IDEA # 2
Use differentiable functions that produce
features efficiently
IDEA # 3
End-to-end learning:
no distinction between feature extractor and classifier
IDEA # 4
“Deep” architectures:
cascade of simpler non-linear modules

- Back propagation : Chin Rule (쪼개는 것) 


### feature selection 

- filter: 통계 방법-feature importance
- wrapper: 기계학습과 동시해해서 back word
- embedded

### Fully connected Neural Net
이미지는 특정 부분 주위에 있는 것과 큰 연관성이 있다. 

### Locally Connected Neural Net
부분적으로 몇개 특징만 보는 것. 이렇게 하면 parameter 개수가 줄어든다. 'Ocam 의 면도날': 성능이 비슷하니깐 간단한걸 쓴다. 

### Convolutional Net
하나의 영역 안에 있는 특징을 찾는다.  
- pooling: 모델이 간단해져 속도가 빨라진다. (요즘엔 스트라이드를 더 쓴다.) 
- Stride: 몇 칸씩 옮기는 것 

### Convolution

In [ ]:
%matplotlib inline

In [5]:
from scipy.ndimage.filters import convolve, correlate

In [7]:
import numpy as np

In [8]:
# 신호처리하는데서 많이 썼었다. 
# np.은 2차원을 계산하지 못한다. 
np.convolve([3],[1,2])
# 3*1, 3*2

array([3, 6])

In [13]:
np.convolve([3,2],[1,2])
# 3*1 ,3*2+2*1, 2*2

array([3, 8, 4])

In [14]:
np.correlate([3],[1,2])
# 3*2, 3*1
# 교차 상관 

array([6, 3])

In [19]:
np.convolve([1,2],[3,4,5])
# 3*1,1*4+2*3, 2*5

array([ 3, 10, 13, 10])

In [28]:
np.correlate([1,2],[3,4,5])
# 5*2 +1*4, 2*4,1*3

array([14, 11])

In [36]:
from scipy.signal import convolve, convolve2d
# convolve 는 2차원도 할 수 있다. 
# 따라서 이걸 더 많이 쓴다. 

In [33]:
convolve([[1,2],[3,4]],[[1,2]])
# 1*1, 1*2+2*1, 2*2
# 3*1, 3*6+4*1, 4*2

array([[ 1,  4,  4],
       [ 3, 10,  8]])

In [39]:
convolve2d([[1,2],[3,4]], [[3,4],[1,2]])

array([[ 3, 10,  8],
       [10, 28, 20],
       [ 3, 10,  8]])

https://keras.io/examples/conv_filter_visualization/

In [80]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
# tensorflow 불러오기 전에 실행시키면 v1 코드를 쓸 수 있다.

In [81]:
import tensorflow as tf 
import time
import numpy as np
from PIL import Image as pil_image
from tensorflow.keras.preprocessing.image import save_img
from tensorflow.keras import layers
from tensorflow.keras.applications import vgg16
from tensorflow.keras import backend as K

In [41]:
tf.sqrt

<function tensorflow.python.ops.gen_math_ops.sqrt(x, name=None)>

In [83]:
# version2가 최근에 나왔기 때문에 v1,2를 나눠서 불러들일 수 있다. 
# tf.compat.v1.keras.backend.epsilon
# tf.compat.v2.keras.backend.epsilon 두개의 버전이 다르다. 
tf.compat.v1.keras.backend.epsilon()

1e-07

In [84]:
tf.compat.v2.keras.backend.epsilon()

1e-07

In [85]:
def normalize(x):
    """utility function to normalize a tensor.

    # Arguments
        x: An input tensor.

    # Returns
        The normalized input tensor.
    """
    return x / (K.sqrt(K.mean(K.square(x))) + K.epsilon())
# zero division을 방지하기 위해서 epsilon 

In [86]:
def deprocess_image(x):
    """utility function to convert a float array into a valid uint8 image.

    # Arguments
        x: A numpy-array representing the generated image.

    # Returns
        A processed numpy-array, which could be used in e.g. imshow.
    """
    # normalize tensor: center on 0., ensure std is 0.25
    x -= x.mean()
    x /= (x.std() + K.epsilon())
    x *= 0.25

    # clip to [0, 1]- 넘파이에서 짤라 내는 것 
    x += 0.5
    x = np.clip(x, 0, 1)

    # convert to RGB array
    x *= 255
# tensorflow는 28,28,1 로 들어가는데 ,티아노는 1, 28, 28로 들어간다. 
    if K.image_data_format() == 'channels_first':
        x = x.transpose((1, 2, 0))
    x = np.clip(x, 0, 255).astype('uint8')
#     0 보다 작으면0 , 255보다 크면 255 
    return x

In [87]:
a = np.array([1,2,3,4,5])

In [88]:
np.where(a>3, 0, -1)
# 조건에 맞으면 0, 안맞으면 -1 

array([-1, -1, -1,  0,  0])

In [89]:
np.clip(a,2,4)
# 2보다 작으면 2, 4보다 크면 4

array([2, 2, 3, 4, 4])

In [90]:
# vector 값을 이미지로 바꿀 때 0-255 사이로 두어야함.
def process_image(x, former):
    """utility function to convert a valid uint8 image back into a float array.
       Reverses `deprocess_image`.

    # Arguments
        x: A numpy-array, which could be used in e.g. imshow.
        former: The former numpy-array.
                Need to determine the former mean and variance.

    # Returns
        A processed numpy-array representing the generated image.
    """
    if K.image_data_format() == 'channels_first':
        x = x.transpose((2, 0, 1))
    return (x / 255 - 0.5) * 4 * former.std() + former.mean()

In [91]:
def visualize_layer(model,
                    layer_name,
                    step=1.,
                    epochs=15,
                    upscaling_steps=9,
                    upscaling_factor=1.2,
                    output_dim=(412, 412),
                    filter_range=(0, None)):
    """Visualizes the most relevant filters of one conv-layer in a certain model.

    # Arguments
        model: The model containing layer_name.
        layer_name: The name of the layer to be visualized.
                    Has to be a part of model.
        step: step size for gradient ascent.
        epochs: Number of iterations for gradient ascent.
        upscaling_steps: Number of upscaling steps.
                         Starting image is in this case (80, 80).
        upscaling_factor: Factor to which to slowly upgrade
                          the image towards output_dim.
        output_dim: [img_width, img_height] The output image dimensions.
        filter_range: Tupel[lower, upper]
                      Determines the to be computed filter numbers.
                      If the second value is `None`,
                      the last filter will be inferred as the upper boundary.
    """
    def _generate_filter_image(input_img,
                               layer_output,
                               filter_index):
        """Generates image for one particular filter.

        # Arguments
            input_img: The input-image Tensor.
            layer_output: The output-image Tensor.
            filter_index: The to be processed filter number.
                          Assumed to be valid.

        #Returns
            Either None if no image could be generated.
            or a tuple of the image (array) itself and the last loss.
        """
        s_time = time.time()

        # we build a loss function that maximizes the activation
        # of the nth filter of the layer considered
        if K.image_data_format() == 'channels_first':
            loss = K.mean(layer_output[:, filter_index, :, :])
        else:
            loss = K.mean(layer_output[:, :, :, filter_index])

        # we compute the gradient of the input picture wrt this loss
        # loss를 input_img 관해서 미분 
        grads = K.gradients(loss, input_img)[0]

        # normalization trick: we normalize the gradient
        grads = normalize(grads)

        # this function returns the loss and grads given the input picture
        iterate = K.function([input_img], [loss, grads])

        # we start from a gray image with some random noise
        intermediate_dim = tuple(
            int(x / (upscaling_factor ** upscaling_steps)) for x in output_dim)
        if K.image_data_format() == 'channels_first':
            input_img_data = np.random.random(
                (1, 3, intermediate_dim[0], intermediate_dim[1]))
        else:
            input_img_data = np.random.random(
                (1, intermediate_dim[0], intermediate_dim[1], 3))
        input_img_data = (input_img_data - 0.5) * 20 + 128

        # Slowly upscaling towards the original size prevents
        # a dominating high-frequency of the to visualized structure
        # as it would occur if we directly compute the 412d-image.
        # Behaves as a better starting point for each following dimension
        # and therefore avoids poor local minima
        for up in reversed(range(upscaling_steps)):
            # we run gradient ascent for e.g. 20 steps
            for _ in range(epochs):
                loss_value, grads_value = iterate([input_img_data])
                input_img_data += grads_value * step

                # some filters get stuck to 0, we can skip them
                if loss_value <= K.epsilon():
                    return None

            # Calculate upscaled dimension
            intermediate_dim = tuple(
                int(x / (upscaling_factor ** up)) for x in output_dim)
            # Upscale
            img = deprocess_image(input_img_data[0])
            img = np.array(pil_image.fromarray(img).resize(intermediate_dim,
                                                           pil_image.BICUBIC))
            input_img_data = np.expand_dims(
                process_image(img, input_img_data[0]), 0)

        # decode the resulting input image
        img = deprocess_image(input_img_data[0])
        e_time = time.time()
        print('Costs of filter {:3}: {:5.0f} ( {:4.2f}s )'.format(filter_index,
                                                                  loss_value,
                                                                  e_time - s_time))
        return img, loss_value

    def _draw_filters(filters, n=None):
        """Draw the best filters in a nxn grid.

        # Arguments
            filters: A List of generated images and their corresponding losses
                     for each processed filter.
            n: dimension of the grid.
               If none, the largest possible square will be used
        """
        if n is None:
            n = int(np.floor(np.sqrt(len(filters))))

        # the filters that have the highest loss are assumed to be better-looking.
        # we will only keep the top n*n filters.
        filters.sort(key=lambda x: x[1], reverse=True)
        filters = filters[:n * n]

        # build a black picture with enough space for
        # e.g. our 8 x 8 filters of size 412 x 412, with a 5px margin in between
        MARGIN = 5
        width = n * output_dim[0] + (n - 1) * MARGIN
        height = n * output_dim[1] + (n - 1) * MARGIN
        stitched_filters = np.zeros((width, height, 3), dtype='uint8')

        # fill the picture with our saved filters
        for i in range(n):
            for j in range(n):
                img, _ = filters[i * n + j]
                width_margin = (output_dim[0] + MARGIN) * i
                height_margin = (output_dim[1] + MARGIN) * j
                stitched_filters[
                    width_margin: width_margin + output_dim[0],
                    height_margin: height_margin + output_dim[1], :] = img

        # save the result to disk
        save_img('vgg_{0:}_{1:}x{1:}.png'.format(layer_name, n), stitched_filters)

    # this is the placeholder for the input images
    assert len(model.inputs) == 1
    input_img = model.inputs[0]

    # get the symbolic outputs of each "key" layer (we gave them unique names).
    layer_dict = dict([(layer.name, layer) for layer in model.layers[1:]])

    output_layer = layer_dict[layer_name]
    assert isinstance(output_layer, layers.Conv2D)

    # Compute to be processed filter range
    filter_lower = filter_range[0]
    filter_upper = (filter_range[1]
                    if filter_range[1] is not None
                    else len(output_layer.get_weights()[1]))
    assert(filter_lower >= 0
           and filter_upper <= len(output_layer.get_weights()[1])
           and filter_upper > filter_lower)
    print('Compute filters {:} to {:}'.format(filter_lower, filter_upper))

    # iterate through each filter and generate its corresponding image
    processed_filters = []
    for f in range(filter_lower, filter_upper):
        img_loss = _generate_filter_image(input_img, output_layer.output, f)

        if img_loss is not None:
            processed_filters.append(img_loss)

    print('{} filter processed.'.format(len(processed_filters)))
    # Finally draw and store the best filters to disk
    _draw_filters(processed_filters)

In [92]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

W1209 16:47:46.354488 14592 deprecation.py:506] From C:\Users\Cho Gyung Ah\Anaconda3\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [93]:
dir(model.layers)
# model.get_layer
# __iter__

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [94]:
# index/slice: sequence 
model.layers[1:3]

In [95]:
model.get_layer

<bound method Network.get_layer of <tensorflow.python.keras.engine.sequential.Sequential object at 0x0000029205FB1208>>

In [96]:
# gradient descent 
x = tf.ones((2,2))

tf.gradient with 랑 같이 쓰면 eager tensor 방시으로 쓰고 with 안쓰면 옛날 방식으로 계산한다.

In [97]:
# __name__: 현재 파일이 import 안될 때 쓴다. 
# __name__: 현재 작업하고 있는 파일에서 name를 치면 __main이 나온다.
# if __name__ == '__main__':
#     # the name of the layer we want to visualize
#     # (see model definition at keras/applications/vgg16.py)
#     LAYER_NAME = 'block5_conv1'

# build the VGG16 network with ImageNet weights
# included_top: fully connected 붙일지 안붙일지
vgg = vgg16.VGG16(weights='imagenet', include_top=False)
print('Model loaded.')
vgg.summary()

Model loaded.
Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, None, None, 3)]   0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, None, None, 64)    1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, None, None, 64)    36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, None, None, 64)    0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, None, None, 128)   73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, None, None, 128)   147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, None, None,

In [99]:
# example function call
visualize_layer(vgg, 'block1_conv2')

Compute filters 0 to 64
Costs of filter   0:   164 ( 54.60s )
Costs of filter   1:    63 ( 51.44s )
Costs of filter   2:   365 ( 51.31s )
Costs of filter   3:   325 ( 48.68s )
Costs of filter   4:   251 ( 49.02s )
Costs of filter   5:   108 ( 49.21s )
Costs of filter   6:    77 ( 51.77s )
Costs of filter   7:   222 ( 48.24s )
Costs of filter   8:   130 ( 53.70s )
Costs of filter   9:    71 ( 60.59s )
Costs of filter  10:   171 ( 51.54s )
Costs of filter  11:   110 ( 55.52s )
Costs of filter  12:    91 ( 56.15s )
Costs of filter  13:   118 ( 52.12s )
Costs of filter  14:    51 ( 51.87s )
Costs of filter  15:   328 ( 51.00s )
Costs of filter  16:   136 ( 61.09s )
Costs of filter  17:   123 ( 51.78s )
Costs of filter  18:   620 ( 50.45s )
Costs of filter  19:   139 ( 54.78s )
Costs of filter  20:   180 ( 53.27s )
Costs of filter  21:    75 ( 52.03s )
Costs of filter  22:    95 ( 52.66s )
Costs of filter  23:    84 ( 55.98s )
Costs of filter  24:   343 ( 51.12s )
Costs of filter  25:   115

KeyboardInterrupt: 

## keras version2로 업데이트 안된게 많다. 

Gan

Transfer learning을 짤 쓰면 그 모델을 가져와서 더 학습시킬 수 있다. (imagenet)

- pythorch -> tensor (model comfort) 
- keras에서 가져오기 (VGG같은 모델: 간단하고 성능이 좋아서, transfer learning 하기가 좋다.) 
- Tensorhub (모델 모아둔 곳: 내가 필요한 모델 불러올 수 있다.)

## Transfer 모델 쓰는 법
https://keras.io/applications/

In [101]:
# Classify ImageNet classes with ResNet50
from keras.applications.resnet50 import ResNet50
from keras.preprocessing import image
from keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np

# layers 50
model = ResNet50(weights='imagenet')

img_path = 'bono.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = model.predict(x)
# decode the results into a list of tuples (class, description, probability)
# (one such list for each sample in the batch)
print('Predicted:', decode_predictions(preds, top=3)[0])
# Predicted: [(u'n02504013', u'Indian_elephant', 0.82658225), (u'n01871265', u'tusker', 0.1122357), (u'n02504458', u'African_elephant', 0.061040461)]

Predicted: [('n03271574', 'electric_fan', 0.5685956), ('n04542943', 'waffle_iron', 0.06175959), ('n04398044', 'teapot', 0.05639047)]


In [ ]:
from tensorflow.keras.applications.vgg16 import VGG16

In [ ]:
vgg = VGG16()

In [ ]:
3 + 4 + 4