In [3]:
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Sequential

In [47]:
from tensorflow.keras.layers import GlobalAveragePooling2D, GlobalMaxPooling2D

In [6]:
import numpy as np

In [41]:
# convolution은 4차원
model = Sequential([
    GlobalAveragePooling2D(input_shape=(4,4,1))
])

In [42]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
global_average_pooling2d_6 ( (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [43]:
x = np.arange(16).reshape(1,4,4,1)

In [44]:
model.predict(x).shape

(1, 1)

In [45]:
np.squeeze(model.predict(x))

array(7.5, dtype=float32)

In [ ]:
model.fit

In [48]:
from tensorflow.keras.datasets import mnist

In [97]:
(X_train,y_train),(X_test, y_test) = mnist.load_data()

In [92]:
X_train = X_train[...,np.newaxis]

In [ ]:
X_train.reshpe(-1,28,28,1)

In [93]:
model = Sequential([
    GlobalMaxPooling2D(input_shape=(28,28,1))
])

In [94]:
model.summary()

Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
global_max_pooling2d_8 (Glob (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [95]:
t = model.predict(X_train)

In [96]:
t.shape
# column이 1개 있다. 
# 784에서 1개로 줄여서 계산 복잡도는 줄었다.
# overfitting을 줄여준다. (feature layer가 성능이 좋을 때만)

(60000, 1)

In [ ]:
(X_train,y_train),(X_test, y_test) = mnist.load_data()

In [98]:
model = Sequential([
    Flatten(input_shape=(28,28))
])

In [99]:
model.predict(X_train).shape
# column이 784개 있다는 것이다. 
# column이 맞다는 것은 특성을 여러가지로 뽑아낼 수 있다는 것이므로 좋다. 

(60000, 784)

In [146]:
a = np.arange(9).reshape(3,3)

In [134]:
a.shape

(1, 3, 3)

In [153]:
model = Sequential([
    Dense(2,input_shape=(3,3)),
    Dense(1)
])

In [136]:
t = model.predict(a)

In [137]:
t.shape

(1, 3, 1)

In [138]:
t

array([[[-1.2890966 ],
        [-0.50054646],
        [ 0.28800392]]], dtype=float32)

In [156]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [219]:
b = np.array([[[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]],
       
           [[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]]])

In [220]:
b.shape

(2, 3, 3)

In [252]:
model = Sequential([
    Dense(2,input_shape=(3,3), use_bias=False, kernel_initializer = 'Ones'),
    Dense(1)
])

# weights : 문자열, tf.nn, 상속 (초기화를 내마음대로 바꿀 수 있다.) 

In [253]:
model.summary()

Model: "sequential_45"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_46 (Dense)             (None, 3, 1)              3         
_________________________________________________________________
dense_47 (Dense)             (None, 3, 1)              2         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [254]:
t = model.predict(b)

In [255]:
t.shape

(2, 3, 1)

In [256]:
t

array([[[ -4.324216],
        [-17.296864],
        [-30.269512]],

       [[ -4.324216],
        [-17.296864],
        [-30.269512]]], dtype=float32)

In [267]:
b = np.array([[[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]]])

In [297]:
model = Sequential([
    Flatten(input_shape=(3,3)),
    Dense(2, kernel_initializer='ones'),
    Dense(2, kernel_initializer = 'ones')
])

# weights : 문자열, tf.nn, 상속 (초기화를 내마음대로 바꿀 수 있다.) 
# C방식: 한 row로 관리하기 때문에 flatten으로 간다. 
# opencv의 2번째 인자, cv=ml_row, ml_col   (행렬이 어떻게 구성되어 있는지에 따라서)

In [298]:
model.summary()

Model: "sequential_58"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_6 (Flatten)          (None, 9)                 0         
_________________________________________________________________
dense_70 (Dense)             (None, 2)                 20        
_________________________________________________________________
dense_71 (Dense)             (None, 2)                 6         
Total params: 26
Trainable params: 26
Non-trainable params: 0
_________________________________________________________________


In [299]:
sum(np.arange(9))*2

72

In [294]:
model.predict(b)

array([[72., 72.]], dtype=float32)

- MobileNetV2

In [300]:
from tensorflow.keras.applications import MobileNetV2

In [389]:
model = MobileNetV2(include_top = False, input_shape=(32,32,3))
# convolution은 channel값이 필요해서 3차원으로 집어넣어야한다. 
# 채널 3맞춰야하는 애가 중간에 있어서 3을 넣어야한다. 

/home/ai52/anaconda3/lib/python3.7/site-packages/keras_applications/mobilenet_v2.py:294: UserWarning: `input_shape` is undefined or non-square, or `rows` is not in [96, 128, 160, 192, 224]. Weights for input shape (224, 224) will be loaded as the default.
  warnings.warn('`input_shape` is undefined or non-square, '


In [391]:
from tensorflow.keras.layers import ReLU

In [390]:
model.summary()

# sequence model인 애와 아닌 애의 차이점 : Connected to 
# Sequence는 단방향만 지원한다. 
# multi_input, multi_output : Connected to 

Model: "mobilenetv2_1.00_224"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_5 (InputLayer)            [(None, 32, 32, 3)]  0                                            
__________________________________________________________________________________________________
Conv1_pad (ZeroPadding2D)       (None, 33, 33, 3)    0           input_5[0][0]                    
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 16, 16, 32)   864         Conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 16, 16, 32)   128         Conv1[0][0]                      
_______________________________________________________________________________

In [317]:
# convolution:이미지 크기와 상관이 없다.
# input_shape를 굳이 안해도된다. 

In [305]:
from tensorflow.keras.models import Model

In [306]:
model2 = Model(inputs = model.inputs, outputs=model.layers[2].output)

In [308]:
model2.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 32, 32, 3)]       0         
_________________________________________________________________
Conv1_pad (ZeroPadding2D)    (None, 33, 33, 3)         0         
_________________________________________________________________
Conv1 (Conv2D)               (None, 16, 16, 32)        864       
Total params: 864
Trainable params: 864
Non-trainable params: 0
_________________________________________________________________


- Input

In [310]:
from tensorflow.keras.layers import Input

In [313]:
input_ = Input(shape=(32,32))
# output_ = Output()

In [314]:
x1 = Dense(2, kernel_initializer='ones')(input_)
# list가 붙여진다.(input, output이 여러개이기 때문에)

In [315]:
model2 = Model(input_, x1)

In [316]:
model2.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 32, 32)]          0         
_________________________________________________________________
dense_72 (Dense)             (None, 32, 2)             66        
Total params: 66
Trainable params: 66
Non-trainable params: 0
_________________________________________________________________


- activation

In [324]:
from tensorflow.keras.layers import Activation

In [393]:
b = np.array([[[0, -1, 2],
       [3, -4, 5],
       [6, -7, 8]]])

In [409]:
model = Sequential([
    Dense(2, input_shape=(3,3), kernel_initializer='ones', activation='relu'),
    Dense(2, kernel_initializer = 'ones'),
#     Activation('relu'), # 앞에 있는거 activation해주는 것 
    ReLU(),
    Flatten()
])

# weights : 문자열, tf.nn, 상속 (초기화를 내마음대로 바꿀 수 있다.) 
# C방식: 한 row로 관리하기 때문에 flatten으로 간다. 
# opencv의 2번째 인자, cv=ml_row, ml_col   (행렬이 어떻게 구성되어 있는지에 따라서)

In [410]:
model.summary()

Model: "sequential_80"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_116 (Dense)            (None, 3, 2)              8         
_________________________________________________________________
dense_117 (Dense)            (None, 3, 2)              6         
_________________________________________________________________
re_lu_5 (ReLU)               (None, 3, 2)              0         
_________________________________________________________________
flatten_28 (Flatten)         (None, 6)                 0         
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [411]:
model.predict(b)

array([[ 2.,  2.,  8.,  8., 14., 14.]], dtype=float32)

In [413]:
from tensorflow.keras.layers import Convolution2D, Conv2D

In [556]:
c = np.arange(100).reshape(10,10)

In [557]:
c = np.concatenate([[[c,c]]])

In [558]:
c = c.reshape(2,10,10,1)

In [654]:
model = Sequential([
    Conv2D(2, (3,3), kernel_initializer = 'ones', input_shape = (10,10,1)),
#     Conv2D(2, (3,3), kernel_initializer = 'ones')    
    GlobalAveragePooling2D()
])

# Conv2D 4차원 
# input_shape 5,5,3 
# filters = kernel = weights

In [655]:
model.summary()

Model: "sequential_112"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_37 (Conv2D)           (None, 8, 8, 2)           20        
_________________________________________________________________
global_average_pooling2d_9 ( (None, 2)                 0         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________


In [656]:
model.predict(c)

array([[445.5, 445.5],
       [445.5, 445.5]], dtype=float32)

In [657]:
model = Sequential([
    Conv2D(2, (3,3), kernel_initializer = 'ones', input_shape = (10,10,1))
#     Conv2D(2, (3,3), kernel_initializer = 'ones')    
#     GlobalAveragePooling2D()
])

# Conv2D 4차원 
# input_shape 5,5,3 
# filters = kernel = weights

In [658]:
np.mean(model.predict(c))
# 필터당 행별로 평균이 나온다. 

445.5

In [646]:
weights, bias = model.layers[0].get_weights()

In [649]:
weights@bias

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]], dtype=float32)

In [643]:
from tensorflow.keras.layers import BatchNormalization, MaxPool2D

In [612]:
model = Sequential([
    Conv2D(2, (3,3), kernel_initializer = 'ones', input_shape = (10,10,1)),
    MaxPool2D()
#     Conv2D(2, (3,3), kernel_initializer = 'ones') , 
#     BatchNormalization()
])

# 학습되지 않는 4개가 있다. 

In [613]:
model.summary()

Model: "sequential_104"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_29 (Conv2D)           (None, 8, 8, 2)           20        
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 4, 4, 2)           0         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________


In [615]:
model.predict(c)

array([[[[198., 198.],
         [216., 216.],
         [234., 234.],
         [252., 252.]],

        [[378., 378.],
         [396., 396.],
         [414., 414.],
         [432., 432.]],

        [[558., 558.],
         [576., 576.],
         [594., 594.],
         [612., 612.]],

        [[738., 738.],
         [756., 756.],
         [774., 774.],
         [792., 792.]]],


       [[[198., 198.],
         [216., 216.],
         [234., 234.],
         [252., 252.]],

        [[378., 378.],
         [396., 396.],
         [414., 414.],
         [432., 432.]],

        [[558., 558.],
         [576., 576.],
         [594., 594.],
         [612., 612.]],

        [[738., 738.],
         [756., 756.],
         [774., 774.],
         [792., 792.]]]], dtype=float32)

In [694]:
from scipy.signal import convolve2d

In [697]:
convolve2d(b,x, mode='valid')

array([[ 54.,  63.,  72.],
       [ 99., 108., 117.],
       [144., 153., 162.]])

In [762]:
x = np.arange(25).reshape(5,5)
b = np.ones((3,3))
x.shape[1]
# 9 = 3*3
a = []
for i in range((x.shape[1]-(b.shape[1]-1))):
    for j in range((x.shape[1]-(b.shape[1]-1))):
        a.append(x[i:i+3,j:j+3])
        
conv = []        
for p in range(9):
    conv.append(np.sum(a[:][p][:]))

print(np.array(conv).reshape(3,3))

[[ 54  63  72]
 [ 99 108 117]
 [144 153 162]]


In [772]:
x = np.arange(25).reshape(5,5)
b = np.ones((3,3))
x.shape[1]
# 9 = 3*3
a = np.zeros((x.shape[0]-b.shape[0]+1, x.shape[1]-b.shape[1]+1))
for i in range((x.shape[1]-(b.shape[1]-1))):
    for j in range((x.shape[1]-(b.shape[1]-1))):
        a[i,j] = np.sum(x[i:i+3,j:j+3])

In [773]:
a

array([[ 54.,  63.,  72.],
       [ 99., 108., 117.],
       [144., 153., 162.]])

In [784]:
def conv(data_size, conv_size):
    x = np.arange(data_size**2).reshape(data_size,data_size)
    b = np.ones((conv_size,conv_size))

    a = np.zeros((x.shape[0]-b.shape[0]+1, x.shape[1]-b.shape[1]+1))
    for i in range((x.shape[1]-(b.shape[1]-1))):
        for j in range((x.shape[1]-(b.shape[1]-1))):
            a[i,j] = np.sum(x[i:i+(x.shape[1]-(b.shape[1]-1)),j:j+(x.shape[1]-(b.shape[1]-1))])
    print(a)

In [789]:
conv(6,3)

[[168. 184. 200. 156.]
 [264. 280. 296. 228.]
 [360. 376. 392. 300.]
 [306. 318. 330. 252.]]
